# Generated by Django 6.0.3 on 2026-04-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=255)),
                ('class_teacher_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.division')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=255)),
                ('admission_date', models.DateField()),
                ('academic_period', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('caste', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='admission_photos')),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=255)),
                ('father_qualification', models.CharField(max_length=255)),
                ('father_income', models.CharField(max_length=255)),
                ('father_mobile', models.CharField(max_length=255)),
                ('father_email', models.EmailField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(max_length=255)),
                ('mother_qualification', models.CharField(max_length=255)),
                ('mother_income', models.CharField(max_length=255)),
                ('mother_mobile', models.CharField(max_length=255)),
                ('mother_email', models.EmailField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_occupation', models.CharField(max_length=255)),
                ('guardian_income', models.CharField(max_length=255)),
                ('guardian_mobile', models.CharField(max_length=255)),
                ('guardian_email', models.EmailField(max_length=255)),
                ('tc_number', models.CharField(max_length=255)),
                ('tc_date', models.DateField()),
                ('school_name', models.CharField(max_length=255)),
                ('previous_class', models.CharField(max_length=255)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.division')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(max_length=255)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
            ],
        ),
    ]
