# Generated by Django 6.0.3 on 2026-04-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_teacherprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='management.class'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='management.department'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='management.division'),
        ),
        migrations.AlterField(
            model_name='classroomsetup',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_setups', to='management.class'),
        ),
        migrations.AlterField(
            model_name='classroomsetup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_setups', to='management.department'),
        ),
        migrations.AlterField(
            model_name='classroomsetup',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_setups', to='management.division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_list', to='management.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='management.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='management.department'),
        ),
    ]
