# Generated by Django 6.0.3 on 2026-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_class_division_alter_admission_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('Senior Secondary', 'Senior Secondary'), ('Secondary', 'Secondary'), ('Middle', 'Middle'), ('Primary', 'Primary'), ('Pre Primary', 'Pre Primary')], default='Primary', max_length=50),
        ),
    ]
