# Generated by Django 6.0.3 on 2026-04-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_class_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(related_name='subjects', to='management.class'),
        ),
    ]
