# Generated by Django 6.0.3 on 2026-04-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_class_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='management.division'),
        ),
    ]
