# Generated by Django 6.0.3 on 2026-04-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_admission_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='management.class'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='management.department'),
        ),
    ]
